version: '3.1'
services:
  sqs-water:
    image: 'rpi-sqs-influx'
    restart: always
    environment:
      GELF_SERVER_IP: 192.168.1.25
      INFLUX_IP: 192.168.1.122
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    secrets:
      - aws_access_key_id 
      - aws_secret_access_key 
    deploy:
      placement:
        constraints:
          - node.role == manager
    #- '/home/craigh/.aws:/home/pi/.aws'

secrets:
  aws_access_key_id:
    external: true
  aws_secret_access_key:
    external: true 
