version: '3.1'
services:
  sqs-water:
    image: 'craigham/rpi-sqs-influx'
    restart: always
    environment:
      GELF_SERVER_IP: 192.168.1.25
      INFLUX_IP: 192.168.1.122
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    ports:
      - "5060:5000"
    secrets:
      - aws_access_key_id 
      - aws_secret_access_key 
      - influx_waterdb_user
      - influx_waterdb_password
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
  aws_access_key_id:
    external: true
  aws_secret_access_key:
    external: true 
  influx_waterdb_user:
    external: true
  influx_waterdb_password:
    external: true
